apiVersion: apps/v1
kind: Deployment
metadata:
  name: mi-api
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mi-api
  template:
    metadata:
      labels:
        app: mi-api
    spec:
      containers:
      - name: mi-api
        image: hashicorp/http-echo    # imagen de prueba, devuelve texto
        args:
          - "-text=Hola desde mi API en EKS!"
        ports:
        - containerPort: 5678